### ISSUE TITLE
平日課題1

### ISSUE THREAD

**Issue by keigo999** [keigo999/camp_weekday_task1#1]
1 指定のURLからリポジトリをfork

2 forkしたリポジトリのissuesが有効にする

3 forkしたリポジトリにIssueの作成

4 forkしたリポジトリからローカルリポジトリにclone

5 masterブランチから派生したtopic-exercise01を作成

6 Railsアプリの作成

7 vendor/bundleをGit対象外にする

8 ステージングエリアに登録後、コミット

9 scaffoldを使用し、ステージングエリアに登録後、コミット

10 topic-exercise01のリモートブランチが作成

11 masterブランチに対してmergeするようにプルリクエスト

12 自分以外のキャンプ生に対してレビュー依頼

**Comment by N-Ryo** [comment]
内容自体は問題ないのですが、Issueのセルフチェックのために、 受け入れ基準 の部分をチェックボックスにしておくことをオススメします！

---

Issue作成時のエディタのメニューバーにリスト形式のアイコンが３つ並んでいると思います。
それぞれ、以下のような機能です。
※知ってたらすみません。

1. 黒点のリスト
2. 数字つきリスト
3. チェックボックスリスト
